### ISSUE TITLE
Create Figma wireframe

### ISSUE THREAD

**Issue by brendanwlau** [os-ucsd/brendies#1]
## Tasks
- [ ] Create the wireframe using Figma (use template, or create your own)
- [ ] Make pull request with an image of your wireframe

## Acceptance Criteria
- [ ] Every view of the application is included in the wireframe
- [ ] All connections between views included, to show the visual flow of the application

## Resources
- TBD
