### ISSUE TITLE
Mock up of Extended Outlier 

### ISSUE THREAD

**Issue by AlexGuan123** [os-ucsd/brendies#2]
## Tasks
- [x] Create layout for project 
- [x] Possible paths user could take visually 
- [x] On figma 

## Acceptance Criteria
- [x] Coherent structure
- [x] Sufficiently detailed visually
