### ISSUE TITLE
Create base architecture for outliner

### ISSUE THREAD

**Issue by SKBost** [os-ucsd/brendies#3]
## Tasks
- [x] Create Figma page for architecture
- [x] Make login flow
- [x] Make signup flow
- [x] Make outliner page flow
- [x] Design basic data structures

## Acceptance Criteria
In the context of a preliminary design for this outliner:
- [x] Login flow accounts for all possible scenarios
- [x] Signup flow accounts for all possible scenarios
- [x] List page flow accounts for all possible scenarios
- [x] Outline page flow accounts for all possible scenarios
- [x] Structures list reasonably describes all data structures that are likely to be necessary 

## Dependencies
N/A

## Resources
N/A
