### ISSUE TITLE
Create the basic list (of outlines) page

### ISSUE THREAD

**Issue by SKBost** [os-ucsd/brendies#6]
## Tasks
- [ ] Make list page
- [ ] Make hardcoded list
- [ ] Make "create list" button
- [ ] Make "sign out" button

## Acceptance Criteria
- [ ] List page created
- [ ] Hardcoded list included
- [ ] "Create list" button included
- [ ] "Sign out" button included

## Dependencies
N/A

## Resources
N/A
