### ISSUE TITLE
Firebase database

### ISSUE THREAD

**Issue by AlexGuan123** [os-ucsd/brendies#8]
## Tasks
- [x] Create firebase database
- [x] Add firebase to code 
- [ ] Update main with new code

## Acceptance Criteria
- [x] Firebase server is working and accessible
